In [ ]:
import pandas as pd

In [36]:
sbti = pd.read_excel('companies-taking-action.xlsx')

In [37]:
sbti.describe()

,Company Name,ISIN,LEI,Near term - Target Status,Near term - Target Classification,Near term - Target Year,Long term - Target Status,Long term - Target Classification,Long term - Target Year,Net-Zero Committed,...,Organization Type,BA1.5,BA1.5 Date,Location,Region,Sector,Date,Target,Target Classification,Extension
count,6157,2174,2702,6157,3487,3443,411,419,414,6157,...,6157,6157,2349,6157,6157,6157,6157,3485,3550,197
unique,6157,2153,2682,3,8,80,1,1,19,2,...,3,2,50,86,6,52,92,3479,12,23
top,(ACIP) Alexandria Company for Industrial Packages,XS1991188548,549300IS9H0W5N2N4K34,Targets Set,1.5°C,2030,Targets Set,1.5°C,2050,No,...,Company,No,01/09/2021,United Kingdom (UK),Europe,Professional Services,01/06/2023,Headline target: Legal and General Group plc p...,The targets covering greenhouse gas emissions ...,Commitment Compliance Policy transitory grace ...
freq,1,3,3,3487,2982,2747,411,419,222,3742,...,4133,3923,142,1002,3285,573,399,4,2926,100

In [38]:
sbti.head()

,Company Name,ISIN,LEI,Near term - Target Status,Near term - Target Classification,Near term - Target Year,Long term - Target Status,Long term - Target Classification,Long term - Target Year,Net-Zero Committed,...,Organization Type,BA1.5,BA1.5 Date,Location,Region,Sector,Date,Target,Target Classification,Extension
0,(ACIP) Alexandria Company for Industrial Packages,NaN,NaN,Targets Set,Well-below 2°C,2030,NaN,NaN,NaN,No,...,Small or Medium Enterprise,No,NaN,Egypt,Africa,Containers and Packaging,01/02/2022,This target was approved using a streamlined t...,The targets covering greenhouse gas emissions ...,NaN
1,100 Percent Group Limited,NaN,NaN,Targets Set,1.5°C,2030,NaN,NaN,NaN,No,...,Small or Medium Enterprise,No,NaN,United Kingdom (UK),Europe,"Trading Companies and Distributors, and Commer...",01/07/2023,This target was approved using a streamlined t...,The targets covering greenhouse gas emissions ...,NaN
2,2 Sisters Food Group,NaN,NaN,Committed,NaN,NaN,NaN,NaN,NaN,Yes,...,Company,Yes,01/11/2022,United Kingdom (UK),Europe,Food and Beverage Processing,01/12/2022,NaN,NaN,NaN
3,24 Ltd,NaN,NaN,Targets Set,1.5°C,2030,NaN,NaN,NaN,No,...,Small or Medium Enterprise,No,NaN,United Kingdom (UK),Europe,"Trading Companies and Distributors, and Commer...",01/02/2023,This target was approved using a streamlined t...,The targets covering greenhouse gas emissions ...,NaN
4,2degrees,NaN,72450039D2LOPG0Z2I07,Committed,NaN,NaN,NaN,NaN,NaN,No,...,Company,No,NaN,New Zealand,Oceania,Telecommunication Services,01/09/2021,NaN,NaN,NaN

In [40]:
missing_values = sbti.isna()

missing_values_count = missing_values.sum()

total_missing_count = missing_values.sum().sum()

print("Missing values in each column:")
print(missing_values_count)

print("\nTotal missing values in the DataFrame:", total_missing_count)

Missing values in each column:
Company Name                            0
ISIN                                 3983
LEI                                  3455
Near term - Target Status               0
Near term - Target Classification    2670
Near term - Target Year              2714
Long term - Target Status            5746
Long term - Target Classification    5738
Long term - Target Year              5743
Net-Zero Committed                      0
Net-Zero Year                        5744
Organization Type                       0
BA1.5                                   0
BA1.5 Date                           3808
Location                                0
Region                                  0
Sector                                  0
Date                                    0
Target                               2672
Target Classification                2607
Extension                            5960
dtype: int64

Total missing values in the DataFrame: 50840

In [41]:
class_counts = sbti['Sector'].value_counts()
print(class_counts)

Professional Services                                                                                                       573
Software and Services                                                                                                       384
Food and Beverage Processing                                                                                                382
Textiles, Apparel, Footwear and Luxury Goods                                                                                382
Electrical Equipment and Machinery                                                                                          344
Construction and Engineering                                                                                                307
Real Estate                                                                                                                 270
Banks, Diverse Financials, Insurance                                                                                        240
Consumer Durables, Household and Personal Products                                                                          239
Trading Companies and Distributors, and Commercial Services and Supplies                                                    218
Automobiles and Components                                                                                                  211
Retailing                                                                                                                   210
Technology Hardware and Equipment                                                                                           206
Chemicals                                                                                                                   181
Containers and Packaging                                                                                                    166
Telecommunication Services                                                                                                  140
Pharmaceuticals, Biotechnology and Life                                                                                     137
Electric Utilities and Independent Power Producers and Energy Traders (including fossil, alternative and nuclear energy)    128
Building Products                                                                                                           116
Hotels, Restaurants and Leisure, and Tourism Services                                                                       115
Forest and Paper Products - Forestry, Timber, Pulp and Paper, Rubber                                                         94
Ground Transportation - Trucking Transportation                                                                              92
Media                                                                                                                        91
Construction Materials                                                                                                       85
Mining - Iron, Aluminum, Other Metals                                                                                        85
Food and Staples Retailing                                                                                                   82
Food Production - Agricultural Production                                                                                    72
Air Freight Transportation and Logistics                                                                                     63
Healthcare Equipment and Supplies                                                                                            49
Semiconductors and Semiconductors Equipment                                                                                  47
Ground Transportation - Railroads Transportation                                                                             46
Solid Waste Management Utilities                                                                                             44
Food Production - Animal Source Food Production                                                                              42
Specialized Consumer Services                                                                                                38
Healthcare Providers and Services, and Healthcare Technology                                                                 37
Specialized Financial Services, Consumer Finance, Insurance Brokerage Firms                                                  35
Homebuilding                                                                                                                 31
Air Transportation - Airlines                                                                                                26
Water Utilities                                                                                                              23
Ground Transportation - Highways and Railtracks                                                                              22
Aerospace and Defense                                                                                                        20
Water Transportation - Water Transportation                                                                                  15
Mining - Other (Rare Minerals, Precious Metals and Gems)                                                                     14
Air Transportation - Airport Services                                                                                        12
Tires                                                                                                                        11
Tobacco                                                                                                                      10
Education Services                                                                                                            9
Water Transportation - Ports and Services                                                                                     8
Textile Manufacturing, Spinning, Weaving & Apparel                                                                            2
Ground Transportation - Trucking  Transportation                                                                              1
Public Agencies                                                                                                               1
Mining - Coal                                                                                                                 1
Name: Sector, dtype: int64

In [42]:
db = pd.read_csv('DBPedia_Companies_Preprocessed.csv')

In [17]:
db.head()

,Unnamed: 0,company,label,industries,keyPeople,founders,hqLocationCountry,revenue,assets,netIncome,foundingYear,type
0,DBPedia_0,http://dbpedia.org/resource/BioNTech,BioNTech,Biotechnology,"Ryan Richardson, Sean Marett, Sierk Poetting, ...","Helmut Jeggle, Michael Motschmann, Thomas Strü...",Germany,17997279300.0,14569226100.0,349375755.3,2008.0,Societas Europaea
1,DBPedia_1,http://dbpedia.org/resource/Royal_Ceramics,Royal Ceramics,Capital good,"A. M. Weerasinghe, Aravinda Perera, H. Amarase...",NaN,Sri Lanka,57545.0,86241.0,13690.0,1990.0,Public company
2,DBPedia_2,http://dbpedia.org/resource/Vodafone_Kabel_Deu...,Vodafone Kabel Deutschland,Telecommunication,Manuel Cubero,NaN,Germany,1742593710.0,2721493346.0,235202539.0,1980.0,Subsidiary
3,DBPedia_3,http://dbpedia.org/resource/Union_Pacific_Corp...,Union Pacific Corporation,NaN,Lance M. Fritz,NaN,United States,21800000000.0,63500000000.0,6500000000.0,1969.0,Public company
4,DBPedia_4,http://dbpedia.org/resource/Vallibel_One,Vallibel One,Conglomerate (company),"Dinusha Bhaskaran, H. Amarasekara",Dhammika Perera,Sri Lanka,96859.0,285210.0,20580.0,2010.0,Public company

In [21]:
. Themissing_values_db = db.isna()

missing_values_count_db = missing_values_db.sum()

total_missing_count_db = missing_values_db.sum().sum()

print("Missing values in each column:")
print(missing_values_count_db)

print("\nTotal missing values in the DataFrame:", total_missing_count_db)

Missing values in each column:
Unnamed: 0              0
company                 0
label                   0
industries           2911
keyPeople            2224
founders             9002
hqLocationCountry    9496
revenue                 0
assets               7323
netIncome            6023
foundingYear         1145
type                 2140
dtype: int64

Total missing values in the DataFrame: 40264

In [25]:
class_counts = db['type'].value_counts()
print(class_counts)

Public company            3169
Subsidiary                 818
Privately held company     688
Private company            617
S.A. (corporation)         367
                          ...
ASUS                         1
Gōdō gaisha                  1
Research group               1
NextEra Energy               1
INEOS                        1
Name: type, Length: 447, dtype: int64

In [27]:
forbes = pd.read_csv('Forbes_2000_top_company_CLNQ11.csv')

In [28]:
forbes.head()

,2022 Ranking,Organization Name,Industry,Country,Year Founded,CEO,Revenue (Billions),Profits (Billions),Assets (Billions),Market Value (Billions),Total Employees
0,1,Berkshire Hathaway,Diversified Financials,United States,1939,Warren Edward Buffett,276.09,89.80,958.78,741.48,372000.0
1,2,ICBC,Banking,China,1984,Shu Gu,208.13,54.03,5518.51,214.42,449296
2,3,Saudi Arabian Oil Company (Saudi Aramco),Oil & Gas Operations,Saudi Arabia,1933,Amin bin Hasan Al-Nasser,400.38,105.36,576.04,2292.08,68493.0
3,4,JPMorgan Chase,Diversified Financials,United States,2000,Jamie Dimon,124.54,42.12,3954.69,374.45,271025.0
4,5,China Construction Bank,Banking,China,2014,Wang Zuji,202.07,46.89,4746.95,181.32,352621

In [29]:
forbes.describe()

,2022 Ranking,Year Founded,Revenue (Billions),Profits (Billions),Assets (Billions),Market Value (Billions)
count,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000,1999.000000
mean,999.818409,1863.992496,23.886628,2.503167,117.176013,38.260675
std,577.098137,421.815723,40.951362,6.160483,363.826515,117.233301
min,1.000000,0.000000,0.000000,-12.050000,0.170000,0.140000
25%,500.500000,1919.000000,5.600000,0.590000,14.800000,7.335000
50%,1000.000000,1971.000000,12.170000,1.060000,32.100000,16.640000
75%,1499.000000,1996.000000,23.730000,2.270000,77.880000,34.720000
max,1999.000000,2022.000000,572.750000,105.360000,5518.510000,2640.320000

In [31]:
missing_values = forbes.isna()  # or df.isnull()

# Optionally, you can sum the missing values to get the count of missing values in each column
missing_values_count = missing_values.sum()

# Optionally, you can also calculate the total count of missing values in the entire DataFrame
total_missing_count = missing_values.sum().sum()

# Display the result
print("Missing values in each column:")
print(missing_values_count)

print("\nTotal missing values in the DataFrame:", total_missing_count)

Missing values in each column:
2022 Ranking               0
Organization Name          0
Industry                   0
Country                    0
Year Founded               0
CEO                        0
Revenue (Billions)         0
Profits (Billions)         0
Assets (Billions)          0
Market Value (Billions)    0
Total Employees            0
dtype: int64

Total missing values in the DataFrame: 0

In [34]:
class_counts = forbes['Industry'].value_counts()
print(class_counts)

Banking                             289
Diversified Financials              146
Construction                        127
Materials                           117
Oil & Gas Operations                106
Insurance                           105
Consumer Durables                    89
Utilities                            83
Business Services & Supplies         82
Chemicals                            75
IT Software & Services               73
Food, Drink & Tobacco                73
Transportation                       70
Retailing                            69
Drugs & Biotechnology                67
Capital Goods                        59
Technology Hardware & Equipment      56
Health Care Equipment & Services     44
Telecommunications Services          43
Trading Companies                    37
Semiconductors                       35
Household & Personal Products        33
Conglomerates                        29
Food Markets                         26
Media                                25
Hotels, Restaurants & Leisure        19
Aerospace & Defense                  18
Food & Drink                          2
Automotive                            2
Name: Industry, dtype: int64

In [35]:
len(class_counts)

29